# tombi: format.rules.table-keys-order = "ascending"

branch_whitelist = []
disable_bump_commit = true
disable_changelog = true
from_latest_tag = false
generate_mono_repository_global_tag = false
generate_mono_repository_package_tags = false
ignore_fixup_commits = false
ignore_merge_commits = false
scopes = [
  "chezmoi",
  "cocogitto",
  "copier",
  "cspell",
  "git",
  "github",
  "jscpd",
  "kde",
  "megalinter",
  "package",
  "pre-commit",
  "script",
  "vscode",
  "zed"
]
skip_ci = "[skip ci]"
skip_untracked = false
