[dra]
asset_pattern = "*x86_64-unknown-linux-gnu.tar.gz"
github = "devmatteini/dra"
pkg_type = "archive"
tag_pattern = "*.*.*"

[lazygit]
asset_pattern = "*linux_x86_64.tar.gz"
github = "jesseduffield/lazygit"
pkg_type = "archive"
tag_pattern = "v*.*.*"

[ludusavi]
asset_pattern = "*linux.tar.gz"
github = "mtkennerly/ludusavi"
pkg_type = "archive"
tag_pattern = "v*.*.*"

[mcfly]
pkg_type = "static"
repo = "pkg-forge-cargo"

[pcloud]
pkg_type = "appimage"
repo = "ivan-hc-am"

[pince]
asset_pattern = "*.AppImage"
github = "korcankaraokcu/PINCE"
pkg_type = "appimage"
tag_pattern = "v*.*.*"

[rclone]
pkg_type = "static"
repo = "bincache"

[rclone_browser]
asset_pattern = "*linux-x86_64.AppImage"
github = "kapitainsky/RcloneBrowser"
pkg_type = "appimage"
tag_pattern = "*.*.*"

[savestate]
asset_pattern = "*.AppImage"
github = "Matteo842/SaveState"
pkg_type = "appimage"

[tldr]
pkg_id = "github.com.tealdeer-rs.tealdeer"
pkg_type = "static"
repo = "bincache"

[use_via]
asset_pattern = "*linux.AppImage"
github = "the-via/releases"
pkg_type = "appimage"
tag_pattern = "v*.*.*"

[yq]
asset_pattern = "yq_linux_amd64"
github = "mikefarah/yq"
pkg_type = "static"
tag_pattern = "v*.*.*"
